# Generated by Django 4.2.27 on 2026-01-19 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedPage',
            fields=[
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rag_index', serialize=False, to='wagtailcore.page')),
                ('page_type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('last_indexed', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField()),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'wagtail_context_search_indexed_page',
                'indexes': [models.Index(fields=['is_active', 'last_modified'], name='wagtail_con_is_acti_ac5cd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChunkMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('text_preview', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='wagtail_context_search.indexedpage')),
            ],
            options={
                'db_table': 'wagtail_context_search_chunk_metadata',
                'indexes': [models.Index(fields=['page', 'chunk_index'], name='wagtail_con_page_id_cc1074_idx')],
            },
        ),
    ]
